env: "local" # local, prod
API_keys:
  telegram: ""
  youtube: ""
logger:
  file_path: "../logs.txt" #keep empty for no log file
postgres_db:
  user: ""
  password: ""
  host: "" #ignored if used by docker
  sslmode: ""
  port: ""