env: "local" # local, prod
API_keys:
  tele_api_key: ""
  yt_api_key: ""
logger:
  logger_file_path: "" #keep empty for no log file
postgress_db:
  user: ""
  password: ""
  host: "" #ignored if used by docker
  sslmode: ""